export const ALL_PRODUCT_REQUESR = "ALL_PRODUCT_REQUESR";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETIALS_REQUESR = "PRODUCT_DETIALS_REQUESR";
export const PRODUCT_DETIALS_SUCCESS = "PRODUCT_DETIALS_SUCCESS";
export const PRODUCT_DETIALS_FAIL = "PRODUCT_DETIALS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
